---
- hosts: all
  become: true
  vars:
    docker_compose_ver: 1.29.2
    first_run: false

  tasks:
    - name: Create folders
      file:
        path: "/srv/gitlab/{{ item }}"
        state: directory
      loop:
        - config
        - data
        - logs

    - name: Copy docker-compose file
      template:
        src: ../templates/gitlab.yml.j2
        dest: ~/docker-compose.yml

      - name: install pip
        apt:
          name: python3-pip
          state: present

      - name: install python dependencies
        pip:
          name:
            - docker
            - docker-compose

      - name: start docker compose
        docker_compose:
          project_src: ~/

      - name: Add gitlab runner
        shell:
          docker run -d --name gitlab-runner \
          --restart always \
          -v /srv/gitlab-runner/config:/etc/gitlab-runner \
          -v /var/run/docker.sock:/var/run/docker.sock \
          gitlab/gitlab-runner:latest
        when: first_run

      - name: Register Gitlab runner
        shell:
          docker exec -it gitlab-runner gitlab-runner register \
          --url http://<your-ip>/ \
          --non-interactive \
          --locked=false \
          --name DockerRunner \
          --executor docker \
          --docker-image alpine:latest \
          --registration-token <your-token> \
          --tag-list "linux,xenial,ubuntu,docker" \
          --run-untagged
        when: first_run
