name: Tests for OTUS homework

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Run packer validation
      run: |
        mv packer packer/variables.json.example packer/variables.json
        packer validate -var-file =packer/variables.json packer/app.json
        packer validate -var-file =packer/variables.json packer/db.json


    - name: Run terraform validate
       run: |
       cd terraform/stage
       mv terraform.tfvars.example terraform.tfvars
       rm backend.tf
       terraform init
       cd ../prod
       mv terraform.tfvars.example terraform.tfvars
       rm backend.tf
       terraform init
       cd ../..
       terraform -chdir=terraform/stage validate
       terraform -chdir=terraform/prod validate

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
      with:
        tflint_version: latest

    - name: Init TFLint
        run: tflint --init

    - name: Run TFLint
        run: |
          tflint terraform/stage
          tflint terraform/prod


      - name: Run ansible-lint
          uses: barolab/action-ansible-lint@master
          with:
            targets: ansible/**/*.yml
